### ISSUE TITLE
[Feature Request] Different package names for nightly builds

### ISSUE THREAD

**Issue by skyGtm** [XiangRongLin/NewPipe-nightly#1]
I think it would be better to have different package names for nightly builds so that both stable and nightly builds can be installed side by side.
So that we don't have to worry about bugs in stable version of NewPipe and at the same time use/test new features in Nightly builds.

**Comment by XiangRongLin** [comment]
I can't do anything about it on my end here.
The main repo needs to allow one to somehow insert a suffix to package name from the command line.

So best open an issue there for that.

**Comment by skyGtm** [comment]
maybe I don't know about the complexity of implementation of purposed feature.
As I see in main repo of NewPipe, in pull request section, people provide debug builds of apk whose package name ends with '.debug'. so adding few parameters in command line during compilation might be sufficient to generate debug builds.

**Comment by XiangRongLin** [comment]
thats not going to work, thats specific for debug builds. If you want that for release builds open an issue in the main repo, because i can't do anything from here without MAJOR effort which i wont make

**Comment by skyGtm** [comment]
I got you.
Looking at the code, I found that converting the line:

https://github.com/XiangRongLin/NewPipe-nightly/blob/bfff17d08316552070daa6504ccf03021441ff6d/.github/workflows/nightly.yml#L35-L36
 - name: Build apk
        run: ./gradlew assembleRelease --stacktrace

to		
		
https://github.com/TeamNewPipe/NewPipe/blob/6277639dedbfeabeb2105095aeb2b2f7c8a3cd6c/.github/workflows/ci.yml#L28-L29
- name: Build debug APK and run Tests
        run: ./gradlew assembleDebug lintDebug testDebugUnitTest --stacktrace
	or 	./gradlew assembleDebug --stacktrace
is just sufficient to generate debug builds.

So, i think the main objective of installing:
1. stable builds (from main repo) and,
2. nightly or debug builds (from this repo) 
sideby-side will been fulfilled.

It doesn't matter if it is release builds or debug builds until the stable and unstable version can be installed side by side.

**Comment by XiangRongLin** [comment]
if you want debug builds, you can just directly grab them from the CI process on push events.

https://github.com/TeamNewPipe/NewPipe/actions?query=workflow%3ACI+event%3Apush

Where if you click on one entry and go to artifacts, can download the apk. That one is even more up-to-date, because it gets run whenever there is a change.

**Comment by XiangRongLin** [comment]
> It doesn't matter if it is release builds or debug builds until the stable and unstable version can be installed side by side.

I didn't intend to have the apks from here be directly used by endusers. It was supposed to showcase how nighly build would work, so that they can be implemented under the TeamNewPipe organization

**Comment by XiangRongLin** [comment]
Upstream was adjusted to allow passing in a suffix, so closing this with https://github.com/XiangRongLin/NewPipe-nightly/commit/e4da63b613a1947055b34e50d419704c99635067

https://github.com/XiangRongLin/NewPipe-nightly/releases/tag/nightly-245 is the first release with the new package id
