### ISSUE TITLE
(Feature Request) Skip creating a release if no changes were made

### ISSUE THREAD

**Issue by peat80** [XiangRongLin/NewPipe-nightly#3]
Would it be possible to somehow check if there was a new commit to newpipe's dev repo before creating a new build and only then release a new nightly?

It wastes space here, increases build numbers, and would make regression testing harder because sometimes identically apks were produced for several days. 🤔

**Comment by XiangRongLin** [comment]
Possible yes, but i probaly won't implement it. The idea of the nightly build is that it runs every night.

Something that could be considered is still running the build, but not releasing it in those cases. But my shell skills are subpar, which would require some time to do that, which i currently don't have.

Edit: Latest commit date can be fetched with `git log -1 --format=%cd` https://stackoverflow.com/a/25564443/13516981
How to continue working with that would require additional research

**Comment by XiangRongLin** [comment]
Should be fixed by https://github.com/XiangRongLin/NewPipe-nightly/commit/cd20f0e1f1ac90d53a9e86ab13da804a2177d3bb
If not please reopen.

Was easier then expected, since git provided an easy way to get commit from the last day. So you could do this step
``` shell
if git log --since=1.days; then
  echo "new_commit=true" >> $GITHUB_ENV
fi 
```
and then add an if condition to all following steps
```
if: env.new_commit == 'true'
```

**Comment by XiangRongLin** [comment]
Seems like its not working like expected 🤔

**Comment by XiangRongLin** [comment]
Hopefully now fixed with https://github.com/XiangRongLin/NewPipe-nightly/commit/4cd6515cd9b722b0c79a1d0dda68b7dad6c6395a

**Comment by XiangRongLin** [comment]
FINALLY, it works...

I know a lot less about shell than i thought i did

https://github.com/XiangRongLin/NewPipe-nightly/commit/54e1188b4bbf82244beb7ae48ae4e6153c71a809
https://github.com/XiangRongLin/NewPipe-nightly/runs/2761136898?check_suite_focus=true

**Comment by peat80** [comment]
Now there are no builds at all it seems. 🤔 🙄

**Comment by XiangRongLin** [comment]
🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 🤦 

Well no wonder, that it doesn't work. Won't work if you check for new commits before you pull the changes...

**Comment by peat80** [comment]
Sounds logical. 🤔 Hope it will work now. 😎👌
