### ISSUE TITLE
(Bug) Nightly features always one release behind

### ISSUE THREAD

**Issue by peat80** [XiangRongLin/NewPipe-nightly#5]
There seems to be some sort of discrepancies between the commit logs and the build number somehow. The nightly apk seems to be always one release behind feature-wise. So for example the apk from build 242 contains the changes mentioned in build 241 description. I hope you understand what i mean. Not a big deal but a bit misleading. 🤔

Anyways, thx for these nightly buils. 😎

**Comment by XiangRongLin** [comment]
Fixed now. The APK was build BEFORE the newest changes were pulled, now it's afterwards.

So with the next release it's going to correct itself. The past releases I'm just leaving as is

**Comment by peat80** [comment]
Thx again. 😎👌
